language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.3
  - nightly
jobs:
  allow_failures:
    - julia: nightly

notifications:
  email:
    recipients:
      - nightly-rse@invenia.ca
    on_success: never
    on_failure: always
    if: type = cron
matrix:
  allow_failures:
    - julia: nightly
