name: IntegrationTest
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request

jobs:
  test:
    name: ${{ matrix.package.repo }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: [1]
        os: [ubuntu-latest]
        package:
          - {user: JuliaDiff, repo: ChainRules.jl}
          - {user: JuliaMath, repo: SpecialFunctions.jl}
          - {user: invenia, repo: BlockDiagonals.jl}
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: x64
      - uses: julia-actions/julia-buildpkg@latest
      - name: Clone Downstream
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.package.user }}/${{ matrix.package.repo }}
          path: downstream
      - name: Load this and run the downstream tests
        shell: julia --project=downstream {0}
        run: |
          using Pkg
          try
            # force it to use this PR's version of the package
            Pkg.develop(PackageSpec(path="."))
            Pkg.update()
          catch err
            err isa Pkg.Resolve.ResolverError || rethrow()
            # If we can't resolve that means this is incompatible by SemVer and this is fine
            # It means we marked this as a breaking change, so we don't need to worry about
            # Mistakenly introducing a breaking change, as we have intentionally made one

            # Note: this doesn't solve all resolver errors, e.g. might be a mutual dependency
            # of this package and a test only dependency of the downstream packagem that are
            # incompatible. And this check only catches resolution failures with main dependencies
            # (plus this package itself) with this package

            @info "Not compatible with this release. No problem." exception=err
            exit(0)  #  Exit immediately, as a success
          end
          Pkg.test()
