name: IntegrationTest
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  test:
    name: ${{ matrix.package.repo }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: [1]
        os: [ubuntu-latest]
        package:
          - {user: JuliaDiff, repo: ChainRules.jl}
          - {user: JuliaMath, repo: SpecialFunctions.jl}
          - {user:  invenia, repo: BlockDiagonals.jl}
          - {user:  invenia, repo: PDMatsExtras.jl}
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: x64
      - uses: julia-actions/julia-buildpkg@latest
      - name: Clone
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.package.user }}/${{ matrix.package.repo }}
          path: ${{ matrix.package.repo }}
      - name: Run the tests
        run: julia --project=${{ matrix.package.repo }} -e "using Pkg; Pkg.develop(PackageSpec(path=\"./\")); Pkg.update(); Pkg.test()"
        shell: bash
