name: JuliaNightly
# Nightly Version of Julia.
# Runs on PRs and pushes to `master`, but seperate workflow to `CI`
# to avoid inclusion in nightly cron build with failure notifications.
on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:

jobs:
  test:
    name: Julia Nightly - Ubuntu - x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: nightly
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
          file: lcov.info
